import React, { useEffect, useRef, useState } from "react";
import SiteNav from "../components/SiteNav";
import MetalWordmark from "../components/MetalWordmark";
import "./software.css";

const WORKSPACE_VIEWS = {
  Today: { label: "TODAY", title: "Pick up where\nyou stopped.", description: "A quiet starting point for the work already in motion.", rows: [["doaor.com", "Continue writing the Software page"], ["rrd", "Review the next milestone"], ["light", "Open the translation notes"]] },
  Projects: { label: "PROJECTS", title: "The right context,\nalready nearby.", description: "Keep projects, their tools, and their next step in one place.", rows: [["doaor.com", "React · Git clean"], ["desktop", "Tauri · 3 saved commands"], ["github-projects", "Python · Last opened Tuesday"]] },
  Tools: { label: "TOOLS", title: "Use what you\nalready know.", description: "Open the editor, terminal, or saved command that matches the job.", rows: [["VS Code", "Preferred for doaor.com"], ["Windows Terminal", "Open in project folder"], ["Git", "Read the working tree"]] },
};
const CAPABILITIES = [["01", "Find your projects", "Choose folders to scan, review what is found, and keep only the projects that belong in your workspace."], ["02", "Open the right tool", "Remember the editor and terminal you prefer for each project instead of rebuilding that choice every time."], ["03", "Keep a useful trail", "Save a note, a command, or a Resume plan so your next session begins with direction."], ["04", "Stay on your machine", "Projects, notes, and activity live locally. No required account. No cloud workspace to maintain."]];

export default function Software() {
  const [view, setView] = useState("Today");
  const [noticeOpen, setNoticeOpen] = useState(false);
  const noticeRef = useRef(null);
  const earlyAccessRef = useRef(null);
  const selected = WORKSPACE_VIEWS[view];
  useEffect(() => { const previous = document.title; document.title = "Software — doaor"; return () => { document.title = previous; }; }, []);
  useEffect(() => { if (noticeOpen) noticeRef.current?.focus(); }, [noticeOpen]);
  const closeNotice = () => { setNoticeOpen(false); requestAnimationFrame(() => earlyAccessRef.current?.focus()); };
  return <main className="software-page">
    <SiteNav currentKey="software" />
    <header className="software-header"><a href="/" aria-label="doaor home" className="software-wordmark"><MetalWordmark font={'700 1.45rem/1 "Montserrat Alternates", "Century Gothic", sans-serif'} /></a><span>DEVELOPER WORKSPACE</span></header>
    <section className="software-hero"><div className="software-hero-copy"><p className="software-kicker">DOAOR DESKTOP</p><h1>Less restarting.<br /><span>More returning.</span></h1><p>DOAOR is a local desktop workspace for the projects, tools, and context you need to get back into the work without losing the thread.</p><div className="software-hero-actions"><button ref={earlyAccessRef} type="button" onClick={() => setNoticeOpen(true)}>Get early access <span>→</span></button><small>Windows first<br />Private preview in progress</small></div></div><div className="software-orbit" aria-hidden="true"><i /><i /><i /><b>↗</b></div></section>
    <section className="software-showcase" aria-labelledby="workspace-title"><div className="software-showcase-copy"><p className="software-kicker">ONE PLACE TO RE-ENTER</p><h2 id="workspace-title">Your projects don’t start from zero.</h2><p>Switch between a few moments in the workspace. Each one is designed to make a return to work feel more immediate.</p><div className="software-view-tabs" role="tablist" aria-label="Workspace previews">{Object.keys(WORKSPACE_VIEWS).map((name) => <button type="button" role="tab" aria-selected={view === name} key={name} onClick={() => setView(name)}>{name}</button>)}</div></div><div className="software-demo" aria-live="polite"><div className="software-demo-bar"><span /><span /><span /><b>doaor workspace</b><em>⌘ K</em></div><div className="software-demo-body"><aside><small>WORKSPACE</small>{Object.keys(WORKSPACE_VIEWS).map((name) => <span className={view === name ? "is-current" : ""} key={name}>{name}</span>)}<hr /><small>QUICK ACTIONS</small><span>Resume</span><span>New note</span></aside><article><p>{selected.label}</p><h3>{selected.title.split("\n").map((line) => <React.Fragment key={line}>{line}<br /></React.Fragment>)}</h3><strong>{selected.description}</strong><div className="software-demo-list">{selected.rows.map(([name, detail]) => <button type="button" key={name}><b>{name.slice(0, 1)}</b><span>{name}<small>{detail}</small></span><em>→</em></button>)}</div></article></div></div></section>
    <section className="software-capabilities" aria-labelledby="capabilities-title"><div className="software-section-heading"><p className="software-kicker">THE WORKSPACE, IN PRACTICE</p><h2 id="capabilities-title">A little less friction<br />every time you return.</h2></div><div className="software-capability-grid">{CAPABILITIES.map(([number, title, body]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{body}</p><i>↗</i></article>)}</div></section>
    <section className="software-flow"><div><p className="software-kicker">A SIMPLE LOOP</p><h2>Leave work<br />easier to resume.</h2></div><ol><li><span>01</span><div><h3>Choose the project</h3><p>See its recent activity, saved notes, Git status, and available tools.</p></div></li><li><span>02</span><div><h3>Do the next useful thing</h3><p>Open your editor, launch a terminal, or run a command in the right folder.</p></div></li><li><span>03</span><div><h3>Set up your return</h3><p>Leave a clear plan behind, then come back without the usual reorientation.</p></div></li></ol></section>
    <section className="software-closing"><p className="software-kicker">COMING TO WINDOWS FIRST</p><h2>Make room for<br />the work itself.</h2><button type="button" onClick={() => setNoticeOpen(true)}>Get early access <span>→</span></button></section>
    <div className={`software-notice ${noticeOpen ? "is-open" : ""}`} aria-hidden={!noticeOpen}><button className="software-notice-backdrop" tabIndex={-1} onClick={closeNotice} aria-label="Close early access notice" /><section ref={noticeRef} tabIndex={noticeOpen ? -1 : undefined} role="dialog" aria-modal="true" aria-labelledby="early-access-title"><p className="software-kicker">EARLY ACCESS</p><h2 id="early-access-title">Not quite ready to ship.</h2><p>The first public build is still in the works. When it is ready, this will become the download—nothing abrupt, nothing to hunt down.</p><button type="button" onClick={closeNotice}>Sounds good <span>→</span></button></section></div>
  </main>;
}
